<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="5.css"?>
<!DOCTYPE student [
<!ELEMENT student_info (h1,h2+,ad+)>
<!ELEMENT ad (label)>
<!ELEMENT usn (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT col (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT label (#PCDATA|usn|name|col|branch|year|email)*>
<!ELEMENT h2 (#PCDATA)>
<!ELEMENT h1 (#PCDATA)>]>

<student_info>
<h1>Student Information</h1>
<h2>Student1</h2>
<ad><label>USN:<usn>4MT16IS001</usn></label></ad>
<ad><label>NAME:<name>Pramod</name></label></ad>
<ad><label>COLLEGE:<col>MITE</col></label></ad>
<ad><label>BRANCH:<branch>ISE</branch></label></ad>
<ad><label>YEAR:<year>2015</year></label></ad>
<ad><label>EMAIL:<email>pramod@gmail.com</email></label></ad>

<h2>Student2</h2>
<ad><label>USN:<usn>4MT16IS002</usn></label></ad>
<ad><label>NAME:<name>Sahana</name></label></ad>
<ad><label>COLLEGE:<col>MITE</col></label></ad>
<ad><label>BRANCH:<branch>ISE</branch></label></ad>
<ad><label>YEAR:<year>2015</year></label></ad>
<ad><label>EMAIL:<email>sahana@gmail.com</email></label></ad>


<h2>Student3</h2>
<ad><label>USN:<usn>4MT16IS003</usn></label></ad>
<ad><label>NAME:<name>Nithin</name></label></ad>
<ad><label>COLLEGE:<col>MITE</col></label></ad>
<ad><label>BRANCH:<branch>ISE</branch></label></ad>
<ad><label>YEAR:<year>2015</year></label></ad>
<ad><label>EMAIL:<email>nithin@gmail.com</email></label></ad>
</student_info>
